{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.components",
    "module": "components-resources",
    "version": "0.0.0-custom-version",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "0.0.0-custom-version"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "0.0.0-custom-version"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.0-custom-version.jar",
          "url": "components-resources-0.0.0-custom-version.jar",
          "size": 8469,
          "sha512": "dcfe4685308c0f5119a692334805d6e0e0ab1192caa0bcee8a80ea4e7f10b82a52439f7a6951dad94331a47438f89f73a8ec1acc5be0fa74a0499907c0ea1974",
          "sha256": "7a1931975f789c70b725a5b1f7808b7a2bdef0685a54d59c10cb2b3b5f4ae717",
          "sha1": "58d24fb0f0e9d4796433a43111ca5ef982932000",
          "md5": "f6c525667d834565051e6a0863fb9d09"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../library-android/0.0.0-custom-version/library-android-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "library-android",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../library-android/0.0.0-custom-version/library-android-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "library-android",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-resources-desktop/0.0.0-custom-version/components-resources-desktop-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-desktop",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-resources-desktop/0.0.0-custom-version/components-resources-desktop-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-desktop",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/0.0.0-custom-version/components-resources-iosArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/0.0.0-custom-version/components-resources-iosArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/0.0.0-custom-version/components-resources-iosSimulatorArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/0.0.0-custom-version/components-resources-iosSimulatorArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/0.0.0-custom-version/components-resources-iosX64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/0.0.0-custom-version/components-resources-iosX64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/0.0.0-custom-version/components-resources-js-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/0.0.0-custom-version/components-resources-js-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/0.0.0-custom-version/components-resources-macosArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/0.0.0-custom-version/components-resources-macosArm64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/0.0.0-custom-version/components-resources-macosX64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "0.0.0-custom-version"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/0.0.0-custom-version/components-resources-macosX64-0.0.0-custom-version.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "0.0.0-custom-version"
      }
    }
  ]
}
